build:
    environment:
        php: 7.2.13
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
filter:
    paths: ["*/database/*"]
checks:
    php:
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
        no_goto: true
        no_short_open_tag: true
        overriding_parameter: true
        properties_in_camelcaps: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
