build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
filter:
    excluded_paths: [database/*]
checks:
    php:
        code_rating: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
        no_goto: true
        no_short_open_tag: true
        overriding_parameter: true
        properties_in_camelcaps: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
tools:
    external_code_coverage: false
    php_analyzer: true
    php_code_coverage: false
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            paths: ['src']
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]